---
# tasks file for deploy

- name: SARLA | Copy agent | Windows
  copy:
    src: "files/{{ sarla_windows_binary }}"
    dest: "{{ sarla_windows_location }}"

# - name: SARLA | Hide agent | Windows
#   win_command: "attrib +h '{{ sarla_windows_location}}'"

# - name: SARLA | Add persistence | Windows
#   win_regedit: 
#     path: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Run'
#     name: "{{ sarla_windows_binary }}"
#     data: "cmd.exe /c {{ sarla_windows_location }}"
#     type: string

- name: SARLA | Run agent | Windows 
  win_shell: 'runas /trustlevel:0x20000 {{ sarla_windows_binary }}'
  async: 45
  poll: 0
  args:
    chdir: 'C:\\Windows\\System32'
